### PR TITLE
Add support for requests behind proxies

### PR DESCRIPTION
**Pull request by gentisaliu**
See issue https://github.com/jstayton/GoogleMapsGeocoder/issues/16.

### CODE REVIEW

**Comment by gentisaliu** [comment]
Untested with proxies that require authentication, because mine does not require one.

**Comment by jstayton** [comment]
Thanks, @gentisaliu, this is helpful to see!

Since this is the first time proxy support has been requested — and I don't need the functionality myself — I'm a bit hesitant to add four variables and 10 methods to the class for such a specific use-case.

That said, what do you think about adding a `$context` param to `#geocode` instead? Then it's generic enough to support anything that can be done with a stream context, and only adds a tiny bit of code.

**Comment by gentisaliu** [comment]
Sure, that works for me as well. One can always subclass it in order to keep the proxy functionality within the class.

**Comment by jstayton** [comment]
Hey @gentisaliu,

#18 should take care of this, which is now in v2.4.0.

**Comment by gentisaliu** [comment]
Thanks!

**Pull request closed without merging**
